### ISSUE TITLE
Questions about text preprocessing.

### ISSUE THREAD

**Issue by MooreAndMoore** [Albert-Ma/PROP#5]
Hello, 
What should I do when cleaning the texts? Should I remove all the numbers, equations and punctuation marks?
Could you provide the codes or a function for text preprocessing?

**Comment by Albert-Ma** [comment]
Hi,
We need to make the pre-training corpus as clean as possible. 
What I have done is removing the invalid characters, words, sentences, and then converting to plain text. 
There is no need to remove the numbers, equations and punctuation marks since they have important roles in constructing a meaningful sentence.
We only discard the numbers and punctuations in sampling representative words. Because in this step, we only need the "words".
Thanks.
