### ISSUE TITLE
Question about your baseline Transformer_ICT

### ISSUE THREAD

**Issue by MooreAndMoore** [Albert-Ma/PROP#6]
Hi, I'm very interested in your work and I am now following your experimental setups.
Is Transformer_ICT implemented by yourself? Could you please provide the pre-trained model of it?
Thank you.

**Comment by Albert-Ma** [comment]
Yes, we implement `Transformer_ICT`  ourselves. Since we contacted the authors of the `ICT`, that model is not available.

Note that our `Transformer_ICT` is pre-trained with `MLM` and `ICT` in a cross-encoder, but they only use `ICT` as the pre-training task and also use a large batch size in a two-tower manner.

 `Transformer_ICT` model will be available soon.
