### ISSUE TITLE
Question about the stem2word file

### ISSUE THREAD

**Issue by zyznull** [Albert-Ma/PROP#9]
Hi, I'm not clear how to produce the stem2word file, can you explain what this file should be produced？Thanks a lot !

**Comment by Albert-Ma** [comment]
To obtain the stem2pos file, you can use `nltk.PorterStemmer()` function to stem word and store to a JSON file like `{stem_word: {word: word count}}`.  And this file will affect the sampling process, e.g. sample stem word first and then choose one original word (based on its frequency). I will update the preprocessing script soon. But I didn't do too much in-depth analysis in our experiment about the impact of using the stemmed word due to limited computational resources.
